server:
  port: 8080
spring:
  application:
    name: spring-boot-sharding-jdbc
sharding:
  jdbc:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://edianlicai4test.mysql.rds.aliyuncs.com:3306/edian_yzd?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: edian_test
        password: edian_test
        driver-class-name: com.mysql.jdbc.Driver
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://edianlicai4test.mysql.rds.aliyuncs.com:3306/edian_yzd?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: edian_test
        password: edian_test
        driver-class-name: com.mysql.jdbc.Driver
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        master-data-source-name: master
        slave-data-source-names: slave
        name: ds
#      sharding:
#        tables:
#          m_order:
#            actual-data-nodes: ds.m_order_${0..2}
#            table-strategy:
#              inline:
#                sharding-column: id
#                algorithm-expression: m_order_${id % 3}
logging:
  level: debug
mybatis:
#  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.heihaier.springbootshardingjdbc.domain
  mapper-locations: classpath:mybatis/**/*.xml