server:
  port: 8080
spring:
  application:
    name: spring-boot-sharding-jdbc
  datasource:
    druid:
      master:
        url: jdbc:mysql://edianlicai4test.mysql.rds.aliyuncs.com:3306/edian_yzd?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: edian_test
        password: 1jevJI19H6AX4x/ijAfnbw/ErEqzhaOY8BRMH7fASFAFxQg1nljokFhes08PqzYSwmcgqOoInFE0GWxGtvOTaA==
        driver-class-name: com.mysql.jdbc.Driver
        connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
        filters: config,stat,wall,slf4j
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 28
      slave:
        url: jdbc:mysql://edianlicai4test.mysql.rds.aliyuncs.com:3306/edian_yzd?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: edian_test
        password: 1jevJI19H6AX4x/ijAfnbw/ErEqzhaOY8BRMH7fASFAFxQg1nljokFhes08PqzYSwmcgqOoInFE0GWxGtvOTaA==
        driver-class-name: com.mysql.jdbc.Driver
        connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
        filters: config,stat,wall,slf4j
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 28
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOWRzXRKwhj0LdZWAWLyp4JTZqEvvEiz6CNs3c6N7+6SIASzzH0fDUsVcWMFl7X3oGPPLYCcvKqRAvQ/uO0Y3XUCAwEAAQ==
sharding:
  jdbc:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://edianlicai4test.mysql.rds.aliyuncs.com:3306/edian_yzd?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: edian_test
        password: edian_test
        driver-class-name: com.mysql.jdbc.Driver
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://rr-2ze79coea5yc8iui0o.mysql.rds.aliyuncs.com:3306/jxm_prod?serverTimezone=Asia/Singapore&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: jxm_prod
        password: jxm_prod
        driver-class-name: com.mysql.jdbc.Driver
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        master-data-source-name: master
        slave-data-source-names: slave
        name: ds_master
logging:
  level: debug
mybatis:
  type-aliases-package: com.heihaier.springbootshardingjdbc.domain
  mapper-locations: classpath:mybatis/*.xml
#  config-location: classpath:mybatis-config.xml